### PR TITLE
Add daily graph and fix minor issue

### LINKED ISSUE #17: Implement Trend Graph for dailySummary
it would be awesome if we have some graph to visualize daily update trend of the virus

### LINKED ISSUE #25: Markers Icon is not accurate
as our icon is circle, and default behaviour of maps marker's icon is on top of coordinate point, this  causes misinterpreted data and unsynchronized behaviour with pulse animation

figuring out how to put the exact center of icon on the coordinate point will fix this issue

### PR DESCRIPTION
**Pull request by rizmaulana**
1. Add daily graph for deltaConfirmed and deltaRecovere https://github.com/rizmaulana/kotlin-mvvm-covid19/issues/17

image

2. Resolve https://github.com/rizmaulana/kotlin-mvvm-covid19/issues/25

3. Add `send feedback` feature, will share link response soon

Seems .gitignore not working properly, will create separate PR to fix them

### CODE REVIEW

**Comment by pandubaraja** [comment]
> 1. Add daily graph for deltaConfirmed and deltaRecovere #17
> 
> image
> 
> 1. Resolve #25
> 2. Add `send feedback` feature, will share link response soon
> 
> Seems .gitignore not working properly, will create separate PR to fix them

Nicely done!! 🎉 🥇

**Comment by rizmaulana** [comment]
> > 1. Add daily graph for deltaConfirmed and deltaRecovere #17
> > 
> > image
> > 
> > 1. Resolve #25
> > 2. Add `send feedback` feature, will share link response soon
> > 
> > Seems .gitignore not working properly, will create separate PR to fix them
> 
> Nicely done!! 🎉 🥇

Thanks mas, need your code review 🙏

File: app/src/main/java/id/rizmaulana/covid19/ui/adapter/viewholders/TextItemViewHolder.kt [hunk 1]
```diff
@@ -5,26 +5,36 @@ import id.rizmaulana.covid19.R
...
+import id.rizmaulana.covid19.util.ext.gone
+import id.rizmaulana.covid19.util.ext.visible
 
 
 data class TextItem(
-    val text: String? = null,
-    val textResId: Int? = null
-): BaseViewItem {
+    val textResId: Int? = null,
+    val textActionResId: Int? = null
```
Comment (pandubaraja) [inline app/src/main/java/id/rizmaulana/covid19/ui/adapter/viewholders/TextItemViewHolder.kt:14]: Niceeee! thank you for removing hardcoded possibility

File: app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphActivity.kt [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+
+class DailyGraphActivity : BaseActivity() {
+
+    private val viewModel by viewModel<DailyGraphViewModel>()
+    private lateinit var binding: ActivityDailyGraphBinding
+    private val dailyAdapter by lazy {
+        DailyAdapter {
+
+        }
+    }
```
Comment (pandubaraja) [inline app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphActivity.kt:30]: How about we use visitable recycler adapter instead @rizmaulana ? So we create component like `OverviewItemViewHolder` for `LineChart`?  In that way we can reuse this functionality on other places

Comment (pandubaraja) [reply app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphActivity.kt:30]: The binding will be in ViewHolder instead and it will make the Activity cleaner.

File: app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphViewModel.kt [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+    private val _dailyItems = MutableLiveData<List<DailyItem>>()
+    val dailyItems: LiveData<List<DailyItem>>
+        get() = _dailyItems
+
+    fun loadDailyData() {
+        /*Assume daily data just got fresh data from remote api on previous page
+          for UX Purpose, we directly load cache
+        */
+        _dailyItems.postValue(CovidDailyDataMapper.transform(appRepository.getCacheDaily().orEmpty()))
```
Comment (pandubaraja) [inline app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphViewModel.kt:36]: This means it can be only refreshed if we go back to previous page right? What if we want to refresh it on the current page? @rizmaulana

File: app/src/main/java/id/rizmaulana/covid19/ui/overview/DashboardViewModel.kt [hunk 4]
```diff
@@ -97,8 +98,8 @@ class DashboardViewModel(
                     with(daily){
                         val dailies = CovidDailyDataMapper.transform(data)
                         if(dailies.isNotEmpty()) {
-                            items.add(TextItem("Daily Updates"))
-                            items.addAll(dailies)
+                                items.add(TextItem(R.string.daily_updates, R.string.show_graph))
```
Comment (pandubaraja) [inline app/src/main/java/id/rizmaulana/covid19/ui/overview/DashboardViewModel.kt:101]: Nicee! 🎉

**Comment by pandubaraja** [comment]
Oh I see you do not make it as view holder because it is like visual map fragment
Sorry for noticing it just now @rizmaulana recycleview only in bottom sheet behavior

File: app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphViewModel.kt (hunk 3 above)
Comment (fajarnuha) [reply app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphViewModel.kt:36]: agree, better to just fetch data from api, and you just need to call the repository

**Comment by fajarnuha** [comment]
actually, i was kinda imagining the other graph, i was more interested in graph showing total number of cases (not daily update) but i notice that's different api and feature, haha, so other than my missed imagination, this PR is good to go, great work @rizmaulana 

just try to consider some suggestion in code review

**Comment by fajarnuha** [comment]
and also dont forget to mark it as Resolve #17

File: app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphViewModel.kt (hunk 3 above)
Comment (rizmaulana) [reply app/src/main/java/id/rizmaulana/covid19/ui/dailygraph/DailyGraphViewModel.kt:36]: What about use cache for first call and then user can pull data from api if they want to fresh data?

**Comment by rizmaulana** [comment]
> Oh I see you do not make it as view holder because it is like visual map fragment
> Sorry for noticing it just now @rizmaulana recycleview only in bottom sheet behavior

Yes, it is. Still don't have idea how to implement view holder with fixed layout 😅

**Comment by pandubaraja** [comment]
> > Oh I see you do not make it as view holder because it is like visual map fragment
> > Sorry for noticing it just now @rizmaulana recycleview only in bottom sheet behavior
> 
> Yes, it is. Still don't have idea how to implement view holder with fixed layout 😅

Me too 😆 ahahahaha

**Review by fajarnuha — APPROVED** [review]

**Comment by pandubaraja** [comment]
Cool image app preview!! @rizmaulana 🎉 🎉 
Please add the pinned feature too on dashboard preview if you have free time 🙏

**Comment by rizmaulana** [comment]
Sure mas @pandubaraja will modif image preview soon 🙏
